[package]
name = "icednano"
version = "0.1.0"
authors = ["nlevy <nicolaspierrelevy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.1"
iced_wgpu = "0.2.3"
iced_winit = "0.1.0"
bytemuck = "1.2.0"
failure = "*"
cgmath = "0.17"
env_logger = "0.7"
serde_json = "1.0.57"
native-dialog = "0.4.2"

[dependencies.codenano]
version = "0.5.1"
features = ["default"]
