[package]
name = "icednano"
version = "0.1.0"
authors = ["nlevy <nicolaspierrelevy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/thenlevy/iced", rev = "2ec72b0db5300df84cc70c79cf395f8c5a3564cb", features=["image"] }
iced_wgpu = { git = "https://github.com/thenlevy/iced", rev = "2ec72b0db5300df84cc70c79cf395f8c5a3564cb" }
iced_graphics = { git = "https://github.com/thenlevy/iced", rev = "2ec72b0db5300df84cc70c79cf395f8c5a3564cb" }
iced_winit = { git = "https://github.com/thenlevy/iced", rev = "2ec72b0db5300df84cc70c79cf395f8c5a3564cb" }
iced_native = { git = "https://github.com/thenlevy/iced", rev = "2ec72b0db5300df84cc70c79cf395f8c5a3564cb" }
ultraviolet = { git = "https://github.com/thenlevy/ultraviolet", rev = "c6af1c4" , features = ["f64", "serde"] }
bytemuck = "1.2.0"
failure = "0.1.8"
env_logger = "0.7"
serde_json = "1.0.57"
native-dialog = "0.4.2"
futures = "0.3.5"
serde = "1.0.116"
serde_derive = "1.0.116"
color_space = "0.5.2"
ab_glyph = "0.2.5"
lyon = { git = "https://github.com/nical/lyon", rev = "ea6d904c6c9ec0445c5653c119a48c43ea76cee9" }
