[package]
name = "icednano"
version = "0.1.0"
authors = ["nlevy <nicolaspierrelevy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/hecrj/iced", rev = "49076c6ac2983e2076dae64f68a2e801904d7ce9", features=["image"] }
iced_wgpu = { git = "https://github.com/hecrj/iced", rev = "49076c6ac2983e2076dae64f68a2e801904d7ce9" }
iced_graphics = { git = "https://github.com/hecrj/iced", rev = "49076c6ac2983e2076dae64f68a2e801904d7ce9" }
iced_winit = { git = "https://github.com/hecrj/iced", rev = "49076c6ac2983e2076dae64f68a2e801904d7ce9" }
iced_native = { git = "https://github.com/hecrj/iced", rev = "49076c6ac2983e2076dae64f68a2e801904d7ce9" }
ultraviolet = { git = "https://github.com/termhn/ultraviolet", rev = "209bedd24903ef59ff85c2056f5b7e9f0a5df64f", features = ["f64", "serde"] }
bytemuck = "1.2.0"
failure = "0.1.8"
env_logger = "0.7"
serde_json = "1.0.57"
native-dialog = "0.4.2"
futures = "0.3.5"
serde = "1.0.116"
serde_derive = "1.0.116"
color_space = "0.5.2"
ab_glyph = "0.2.5"
